FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

COPY ./package*.json ./
RUN npm install

COPY ./ .
RUN echo "Checking scripts directory..." && ls -l scripts && echo "Checking public directory..." && ls -l public
RUN npm run build

FROM alpine AS export
WORKDIR /result
COPY --from=build /app/dist ./html