# docker-compose.test.yml for React
FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
RUN npm rebuild esbuild

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
