FROM node:20-alpine AS build

WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY ./ .
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

CMD cp -r build result_build
# RUN mkdir -p /result_build && cp -r build/* /result_build/