FROM node:20-alpine AS build

WORKDIR /app

RUN apk add --no-cache git
ARG VITE_APP_VERSION
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

COPY ./package*.json ./
RUN npm install

COPY ./ .

RUN npm run build

FROM alpine AS export
WORKDIR /result
COPY --from=build /app/dist ./html