services:
  backend:
    build:
      context: ./washpr
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./washpr:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true