services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    expose:
      - "8000"
    env_file:
      - .env.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: https://api.sokov.eu/api
    container_name: frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
