services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_converted_dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=washservice
      - POSTGRES_USER=washadmin
      - POSTGRES_PASSWORD=secret123
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./minio_data:/data

  backend:
    build:
      context: ./washpr
      dockerfile: Dockerfile
    ports:
      - "8800:8000"
    volumes:
      - ./washpr:/app
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=washservice
      - POSTGRES_USER=washadmin
      - POSTGRES_PASSWORD=secret123
    depends_on:
      - postgres
      - redis
      - minio
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  celery:
    build:
      context: ./washpr
      dockerfile: Dockerfile
    command: celery -A washpr worker --loglevel=info
    volumes:
      - ./washpr:/app
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build:
      context: ./washpr
      dockerfile: Dockerfile
    command: celery -A washpr beat --loglevel=info
    volumes:
      - ./washpr:/app
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set myminio http://minio:9000 minioadmin minioadmin123;
        mc mb -p myminio/washservice;
        mc policy set public myminio/washservice;
        exit 0;
      "

volumes:
  postgres_data:
  minio_data:
