services:
  backend:
    build:
      context: ./washpr
      dockerfile: Dockerfile
    ports:
      - "8800:8000"
    volumes:
      - ./washpr:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata landing.json &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5175:5173"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true