from django.db import models


class LandingPage(models.Model):
    # text for translation
    lang = models.CharField("language prefix", max_length=100)
    prefix = models.CharField("language name", max_length=10)
    # header section
    header_home = models.CharField("Home", max_length=100)
    header_login = models.CharField("login", max_length=100)
    header_logout = models.CharField("logout", max_length=100)
    header_account = models.CharField("account", max_length=100)
    header_panel = models.CharField("panel", max_length=100, blank=True, null=True)
    # menu section
    menu_about_us = models.CharField("about us", max_length=100)
    menu_technology = models.CharField("technology", max_length=100)
    menu_prices = models.CharField("prices", max_length=100)
    menu_services = models.CharField("services", max_length=100)
    menu_linen_rent = models.CharField("linen rent", max_length=100)
    menu_vacancies = models.CharField("vacancies", max_length=100)
    menu_contacts = models.CharField("contact", max_length=100)
    menu_button_request_call = models.CharField("button request call", max_length=100)
    # top banner section
    start_banner_title = models.CharField("banner title", max_length=200)
    start_banner_description = models.TextField("description", max_length=500)
    start_banner_button_request_call = models.CharField("button request call", max_length=100)
    start_banner_button_two = models.CharField("button second", max_length=100)
    # about us section
    about_us_title = models.CharField("title", max_length=200)
    about_us_description = models.TextField("description", max_length=1000)
    about_us_guarantee_quality = models.CharField("guarantee_quality", max_length=100)
    about_us_fast_service = models.CharField("fast service", max_length=100)
    about_us_round_clock_service = models.CharField("round the clock service", max_length=100)
    about_us_super_quality = models.CharField("super_quality", max_length=100)
    # service section
    service_title = models.CharField("title", max_length=200)
    service_sub_title_1 = models.CharField("sub title 1", max_length=200)
    service_description_1 = models.TextField("description 1", max_length=1000)
    service_sub_title_2 = models.CharField("sub title 2", max_length=200)
    service_description_2 = models.TextField("description 2", max_length=1000)
    service_sub_title_3 = models.CharField("sub title 3", max_length=200)
    service_description_3 = models.TextField("description 3", max_length=1000)
    service_sub_title_4 = models.CharField("sub title 4", max_length=200)
    service_description_4 = models.TextField("description 4", max_length=1000)
    service_sub_title_5 = models.CharField("sub title 5", max_length=200)
    service_description_5 = models.TextField("description 5", max_length=1000)
    # technologies section
    technologies_title = models.CharField("title", max_length=200)
    technologies_description = models.TextField("main description", max_length=500)
    technologies_sub_title_1 = models.CharField("sub title 1", max_length=200)
    technologies_description_1 = models.TextField("description 1", max_length=500)
    technologies_sub_title_2 = models.CharField("sub title 2", max_length=200)
    technologies_description_2 = models.TextField("description 2", max_length=500)
    technologies_sub_title_3 = models.CharField("sub title 3", max_length=200)
    technologies_description_3 = models.TextField("description 3", max_length=500)
    technologies_sub_title_4 = models.CharField("sub title 4", max_length=200)
    technologies_description_4 = models.TextField("description 4", max_length=500)
    technologies_sub_title_5 = models.CharField("sub title 5", max_length=200)
    technologies_description_5 = models.TextField("description 5", max_length=500)
    technologies_sub_title_6 = models.CharField("sub title 6", max_length=200)
    technologies_description_6 = models.TextField("description 6", max_length=500)
    # price section
    price_title = models.CharField("title", max_length=200)
    price_description = models.TextField("main description", max_length=500)
    price_button_text = models.CharField("button text", max_length=100)
    # contact section
    contacts_title = models.CharField("title", max_length=200)
    contacts_company_address = models.TextField("company address", max_length=500)
    contacts_laundry_address = models.TextField("laundry address", max_length=500)
    contacts_form_name = models.CharField("form name", max_length=100)
    contacts_form_email = models.CharField("form email", max_length=100)
    contacts_form_phone = models.CharField("form phone", max_length=100)
    contacts_form_message = models.CharField("form message", max_length=100)
    contacts_button_text = models.CharField("button text", max_length=100)
    contacts_agree = models.TextField("I agree", max_length=500)
    contacts_agree_link = models.CharField("agree link", max_length=100)
    contacts_map_link = models.TextField("map link", max_length=1000)
    # footer section
    footer_cookies = models.CharField("cookies", max_length=100)
    footer_cookies_link = models.CharField("cookies", max_length=100)
    footer_privacy_policy = models.CharField("privacy policy", max_length=100)
    footer_privacy_policy_link = models.CharField("privacy policy link", max_length=100)
    # authentication section
    auth_login = models.CharField("log in", max_length=100, blank=True, null=True)
    auth_logout = models.CharField("log out", max_length=100, blank=True, null=True)
    auth_pass_reset = models.CharField("reset password", max_length=100, blank=True, null=True)
    auth_log_data = models.CharField("login data", max_length=100, blank=True, null=True)
    auth_email = models.CharField("your email", max_length=100, blank=True, null=True)
    auth_pass = models.CharField("password", max_length=100, blank=True, null=True)
    auth_no_account = models.CharField("Don't have an account yet", max_length=150, blank=True, null=True)
    auth_create_one = models.CharField("Create one", max_length=150, blank=True, null=True)
    auth_forgot = models.CharField("Forgot pass", max_length=150, blank=True, null=True)
    auth_reg = models.CharField("Create account", max_length=150, blank=True, null=True)
    auth_check_email = models.CharField("User created. Check your email", max_length=150, blank=True, null=True)
    auth_activate = models.CharField("Account activated successfully", max_length=150, blank=True, null=True)
    auth_activate_error = models.CharField("Activation error", max_length=150, blank=True, null=True)
    auth_failed_server = models.CharField("Failed to contact the server", max_length=150, blank=True, null=True)
    auth_invalid_link = models.CharField("Invalid or expired token", max_length=150, blank=True, null=True)
    auth_button_ok = models.CharField("Log in", max_length=100, blank=True, null=True)
    auth_button_error = models.CharField("Back to web site if error", max_length=100, blank=True, null=True)
    auth_author_error = models.CharField("Authorization error", max_length=100, blank=True, null=True)
    auth_unknown_error = models.CharField("Unknown error", max_length=50, blank=True, null=True)
    auth_network_error = models.CharField("Network error", max_length=50, blank=True, null=True)
    # customer info
    customer_full_name = models.CharField("Name and surname", max_length=200, blank=True, null=True)
    customer_company_name = models.CharField("Company name", max_length=200, blank=True, null=True)
    customer_company_number = models.CharField("Company number", max_length=200, blank=True, null=True)
    customer_vat_number = models.CharField("VAT EU number", max_length=200, blank=True, null=True)
    customer_phone = models.CharField("Phone number", max_length=200, blank=True, null=True)
    customer_company_address = models.CharField("Company address", max_length=200, blank=True, null=True)
    customer_vop = models.CharField("VOP", max_length=200, blank=True, null=True)
    customer_terms_use = models.CharField("Terms of use", max_length=200, blank=True, null=True)
    customer_gdpr = models.CharField("GDPR", max_length=200, blank=True, null=True)
    customer_vop_check = models.CharField("VOP read", max_length=200, blank=True, null=True)
    customer_terms_use_check = models.CharField("Terms of use read", max_length=200, blank=True, null=True)
    customer_gdpr_check = models.CharField("GDPR read", max_length=200, blank=True, null=True)
    customer_uploaded_files = models.CharField("Uploaded files", max_length=200, blank=True, null=True)
    customer_important_files = models.CharField("Important files", max_length=200, blank=True, null=True)
    customer_send_to_check = models.CharField("Send to check", max_length=200, blank=True, null=True)
    customer_wait_for_active = models.CharField("Wait for activation", max_length=200, blank=True, null=True)
    customer_your_places = models.CharField("Title Your places", max_length=200, blank=True, null=True)
    customer_you_dont_have_place = models.CharField("Title You don't have any place", max_length=200, blank=True, null=True)
    new_data_change = models.CharField("New data changing", max_length=200, blank=True, null=True)
    new_data_wait = models.CharField("New data waiting for comfirm", max_length=200, blank=True, null=True)
    new_data_faktur = models.CharField("New data for invoices", max_length=200, blank=True, null=True)
    # buttons
    button_submit = models.CharField("Button submit", max_length=50, blank=True, null=True)
    button_cancel = models.CharField("Button cancel", max_length=50, blank=True, null=True)
    button_upload = models.CharField("Button upload file", max_length=50, blank=True, null=True)
    button_uploading = models.CharField("Button uploading", max_length=50, blank=True, null=True)
    button_add_place = models.CharField("Button add new place", max_length=100, blank=True, null=True)
    button_all_history = models.CharField("Button all history", max_length=100, blank=True, null=True)
    button_invoices = models.CharField("Button invoices", max_length=100, blank=True, null=True)
    button_new_order = models.CharField("Button new order", max_length=100, blank=True, null=True)
    button_details = models.CharField("Button details", max_length=100, blank=True, null=True)
    button_back = models.CharField("Button back", max_length=100, blank=True, null=True)
    # messages
    message_file_ok = models.CharField("File uploaded successfully!", max_length=100, blank=True, null=True)
    message_file_size = models.CharField("The selected file exceeds the maximum size of 2MB", max_length=100,
                                         blank=True, null=True)
    message_file_del_quest = models.CharField("Are you sure you want to delete this file?", max_length=100, blank=True,
                                              null=True)
    message_file_failed = models.CharField("Failed to upload file", max_length=100, blank=True, null=True)
    message_file_try_again = models.CharField("An error occurred while uploading the file. Please try again",
                                           max_length=200, blank=True, null=True)
    message_file_deleted = models.CharField("File deleted successfully!", max_length=100, blank=True, null=True)
    message_file_failed_delete = models.CharField("Failed to delete the file", max_length=100, blank=True, null=True)
    message_file_failed_while_deleting = models.CharField("An error occurred while deleting the file", max_length=100,
                                                          blank=True, null=True)
    # order
    order_type_sipping_clear_for_dirty = models.CharField("Order type sipping clear for dirty", max_length=100,
                                                          blank=True, null=True)
    order_type_sipping_1_in_3 = models.CharField("Order type sipping 1 in 3", max_length=100, blank=True, null=True)
    order_one_time = models.CharField("One time order", max_length=100, blank=True, null=True)
    order_quick = models.CharField("Quick order", max_length=100, blank=True, null=True)
    order_note_sh_cl_dr = models.TextField("Note for sipping clear for dirty", max_length=500, blank=True, null=True)
    order_note_sh_1_3 = models.TextField("Note for sipping 1 in 3", max_length=500, blank=True, null=True)
    order_note_one_time = models.TextField("Note for one time", max_length=500, blank=True, null=True)
    order_note_quick = models.TextField("Note for quick order", max_length=500, blank=True, null=True)
    order_note_every_week = models.TextField("Note for every week", max_length=500, blank=True, null=True)
    order_mon_wed_fri = models.CharField("Monday Wednesday Friday", max_length=100, blank=True, null=True)
    order_tue_thu = models.CharField("Tuesday Thursday", max_length=100, blank=True, null=True)
    order_every_day = models.CharField("Every day", max_length=100, blank=True, null=True)
    order_own_system = models.CharField("Order own system", max_length=100, blank=True, null=True)
    order_day_next_visit = models.CharField("Order: Day of next visit", max_length=100, blank=True, null=True)
    order_info_waiting = models.CharField("Order: Information is waiting for update", max_length=100, blank=True, null=True)
    order_status = models.CharField("Order status", max_length=100, blank=True, null=True)
    order_current_order = models.CharField("Order: Current order", max_length=100, blank=True, null=True)

    form_add_place = models.CharField("Form title add new place", max_length=100, blank=True, null=True)
    form_place_name = models.CharField("Form place name", max_length=100, blank=True, null=True)
    form_rp_city = models.CharField("Form RP city", max_length=100, blank=True, null=True)
    form_rp_street = models.CharField("Form RP street", max_length=100, blank=True, null=True)
    form_rp_zip = models.CharField("Form RP zip", max_length=100, blank=True, null=True)
    form_rp_number = models.CharField("Form RP number", max_length=100, blank=True, null=True)
    form_rp_person = models.CharField("Form RP person", max_length=100, blank=True, null=True)
    form_rp_email = models.CharField("Form RP email", max_length=100, blank=True, null=True)
    form_rp_phone = models.CharField("Form RP phone", max_length=100, blank=True, null=True)
    form_create_order = models.CharField("Form create new order", max_length=100, blank=True, null=True)
    form_place = models.CharField("Form place", max_length=100, blank=True, null=True)
    form_type_ship = models.CharField("Form type shipping", max_length=100, blank=True, null=True)
    form_system = models.CharField("Form system", max_length=100, blank=True, null=True)
    form_start_day = models.CharField("Form start day", max_length=100, blank=True, null=True)
    form_note = models.CharField("Form note", max_length=100, blank=True, null=True)
    form_type_note = models.CharField("Form type note", max_length=100, blank=True, null=True)
    form_select_place = models.CharField("Form select place", max_length=100, blank=True, null=True)
    form_select_type = models.CharField("Form select type", max_length=100, blank=True, null=True)
    form_select_system = models.CharField("Form select system", max_length=100, blank=True, null=True)
    form_close = models.CharField("Form close", max_length=100, blank=True, null=True)
    form_monday = models.CharField("Form monday", max_length=100, blank=True, null=True)
    form_tuesday = models.CharField("Form tuesday", max_length=100, blank=True, null=True)
    form_wednesday = models.CharField("Form wednesday", max_length=100, blank=True, null=True)
    form_thursday = models.CharField("Form thursday", max_length=100, blank=True, null=True)
    form_friday = models.CharField("Form friday", max_length=100, blank=True, null=True)
    form_saturday = models.CharField("Form saturday", max_length=100, blank=True, null=True)
    form_sunday = models.CharField("Form sunday", max_length=100, blank=True, null=True)

    place_detail_title = models.CharField("Place title", max_length=100, blank=True, null=True)
    place_address = models.CharField("Place address", max_length=100, blank=True, null=True)
    place_edit_place = models.CharField("Place edit place", max_length=100, blank=True, null=True)



    def __str__(self):
        return self.lang

    class Meta:
        verbose_name = 'Landing page content. Language'
        verbose_name_plural = 'Landing page content. Languages'
