# Generated by Django 5.1.3 on 2025-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="history_order_was_canceled",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Order was canceled"
            ),
        ),
    ]
