# Generated by Django 5.1.3 on 2025-01-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='auth_activate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Account activated successfully'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_activate_error',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Activation error'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_button_error',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Back to web site if error'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_button_ok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Log in'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_check_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='User created. Check your email'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_create_one',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Create one'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='your email'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_failed_server',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Failed to contact the server'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_forgot',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Forgot pass'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_invalid_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Invalid or expired token'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_login',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='log in'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_no_account',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Don't have an account yet"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_pass',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_reg',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Create account'),
        ),
    ]
