# Generated by Django 5.1.3 on 2025-01-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landingpage_auth_activate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='auth_author_error',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Authorization error'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_network_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='network error'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='auth_unknown_error',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='unknown error'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='auth_button_error',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Back to web site if error'),
        ),
    ]
