# Generated by Django 5.1.3 on 2025-01-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_landingpage_auth_author_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='customer_company_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company address'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_company_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company number'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name and surname'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_gdpr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='GDPR'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_gdpr_check',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='GDPR read'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_terms_use',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Terms of use'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_terms_use_check',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Terms of use read'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_vat_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VAT EU number'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_vop',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VOP'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='customer_vop_check',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VOP read'),
        ),
    ]
