# Generated by Django 5.1.3 on 2025-01-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_landingpage_customer_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='button_submit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button submit'),
        ),
    ]
