# Generated by Django 5.1.3 on 2025-01-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_landingpage_button_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='button_upload',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button upload file'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='button_uploading',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button uploading'),
        ),
    ]
