# Generated by Django 5.1.3 on 2025-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_landingpage_button_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='message_file_del_quest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Are you sure you want to delete this file?'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='message_file_deleted',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File deleted successfully!'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='message_file_failed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Failed to upload file'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='message_file_failed_delete',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Failed to delete the file'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='message_file_failed_while_deleting',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='An error occurred while deleting the file'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='message_file_ok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File uploaded successfully!'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='message_file_try_again',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='An error occurred while uploading the file. Please try again'),
        ),
    ]
