# Generated by Django 5.1.3 on 2025-01-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_landingpage_message_file_del_quest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='message_file_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='The selected file exceeds the maximum size of 2MB'),
        ),
    ]
